name: "iOS Market Information"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: IDの生成
      id: build-id
      run: |
        echo "name=id::$(date +%s)" >> $GITHUB_OUTPUT
    - name: Cache
      id: cache
      uses: actions/cache@v3
      with:
        path: version.txt
        key: version-${{ steps.build-id.outputs.id }}
        restore-keys: version-
    - name: Current Version
      id: current_version
      run: |
        if [ -e version.txt ]; then
            echo "version.txtが存在します：$(cat version.txt)"
            if [ $(cat version.txt) = "null" ]
            then
                echo "verion.txtの値がnullのため、0.0.0を出力します"
                echo "version=0.0.0" >> $GITHUB_OUTPUT
            else
                echo "verion.txtの値を出力します"
                echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT
            fi
        else
            echo "version=0.0.0"
        fi
    - name: Check Version
      run: |
        echo ${{ steps.current_version.outputs.version }}
    - name: iOS Market Information
      id: appstore_information
      uses: tarappo/market_app_info@main
      with:
        bundle_identifier: "com.facebook.Facebook"
        version_number: ${{ steps.current_version.outputs.version }}
    - name: Latest Market Information Ouputs
      id: latest_output
      run: |
        echo ${{ steps.appstore_information.outputs.app_name }}
        echo ${{ steps.appstore_information.outputs.release_date }}
        echo ${{ steps.appstore_information.outputs.version }}

        # 値がある場合は、version.txtを更新する
        if [ "${{ steps.appstore_information.outputs.version }}" != "null" ]; then
            echo "version.txtを更新します：${{ steps.appstore_information.outputs.version }}"
            echo ${{ steps.appstore_information.outputs.version }} > version.txt
            echo "new_version=$(cat version.txt)" >> $GITHUB_OUTPUT
        else
            echo "最新バージョンはありませんでした"
        fi
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
            {
            "text": "最新バージョン：${{ steps.latest_output.outputs.new_version }}",
            "blocks": [
                {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": "最新バージョン：${{ steps.latest_output.outputs.new_version }}"
                }
                }
            ]
            }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
